name:                prismatic
version:             0.1.0.0
github:              "lgastako/prismatic"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2019 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         README at <https://github.com/lgastako/prismatic#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- colour
- lens
- string-conversions
- text
- word8

library:
  source-dirs: src

executables:
  prismatic:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - prismatic

tests:
  prismatic-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - lens-aeson
    - prismatic
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-hedgehog
